basePath: /
definitions:
  app.Credentials:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  app.IDResponse:
    properties:
      id:
        type: integer
    type: object
  app.JWTTokenResp:
    properties:
      token:
        type: string
    type: object
  app.Message:
    properties:
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: alexander.egurnov@gmail.com
    name: Alexander Egurnov
  description: This API allows to store and solve simple mazes
  title: Maze API
  version: "0.1"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Login with username and password, get a token to use for further
        operations.
      operationId: login
      parameters:
      - description: Credentials
        in: body
        name: email
        required: true
        schema:
          $ref: '#/definitions/app.Credentials'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.JWTTokenResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/app.Message'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/app.Message'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Message'
      summary: Login to the API
      tags:
      - Auth
  /user:
    post:
      consumes:
      - application/json
      description: Provide a unique username and password to create a new user.
      operationId: CreateUser
      parameters:
      - description: New user credentials
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/app.Credentials'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/app.IDResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/app.Message'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/app.Message'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Message'
      summary: Register a new user for the API
      tags:
      - Auth
schemes:
- http
securityDefinitions:
  bearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
